[build-system]
requires = [
    "wheel",
    "setuptools",
    "cython>=0.29.2",
    "numpy>=2.0.0",
]
build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
markers = [
    "might_download: marks tests that might download a file",
]
